services:
  autossh:
    image: jnovack/autossh
    profiles:
      - vsc-haf-autossh
    environment:
      - SSH_REMOTE_USER=${AUTOSSH_REMOTE_USER}
      - SSH_REMOTE_HOST=${AUTOSSH_REMOTE_HOST}
      - SSH_REMOTE_PORT=${AUTOSSH_REMOTE_PORT:-22}
      - SSH_BIND_IP=0.0.0.0
      - SSH_TUNNEL_PORT=${AUTOSSH_TUNNEL_PORT:-5001}
      - SSH_TARGET_PORT=${AUTOSSH_TARGET_PORT:-5101}
      - SSH_MODE=-L
    restart: always
    ports:
      - 5001:${AUTOSSH_TUNNEL_PORT:-5001}
    volumes:
      - ${AUTOSSH_ID_FILE}:/id_rsa
      - ${AUTOSSH_KNOWN_HOSTS_FILE}:/known_hosts
    networks:
      haf-network: