services:
  vsc-test-install:
    image: vsc-mainnet-haf:${VSC_TEST_VERSION:-dev}
    profiles:
      - apps
      - vsc-test
    environment:
      POSTGRES_HOST: haf
    command:
      - install_app
    networks:
      haf-network:
    depends_on:
      haf:
        condition: service_healthy
  vsc-test-uninstall:
    image: vsc-mainnet-haf:${VSC_TEST_VERSION:-dev}
    profiles:
      - vsc-test-uninstall
    environment:
      POSTGRES_HOST: haf
    command:
      - uninstall_app
    networks:
      haf-network:
    depends_on:
      haf:
        condition: service_healthy
  vsc-test-block-processing:
    image: vsc-mainnet-haf:${VSC_TEST_VERSION:-dev}
    profiles:
      - apps
      - vsc-test
    environment:
      POSTGRES_URL: postgresql://vsc_owner@haf/haf_block_log
      VSC_MAINNET_HAF_LOG_LEVEL: ${VSC_TEST_LOG_LEVEL:-trace}
    command:
      - process_blocks
    healthcheck:
      test: ["CMD-SHELL","/app/scripts/block_processing_healthcheck.sh || exit 1"]
      interval: 10s
      timeout: 2s
      retries: 10
      start_period: 15m
    networks:
      haf-network:
    depends_on:
      vsc-test-install:
        condition: service_completed_successfully
      haf:
        condition: service_healthy
  vsc-test-subindexer:
    image: vsc-mainnet-haf:${VSC_TEST_VERSION:-dev}
    profiles:
      - apps
      - vsc-mainnet-haf
    environment:
      POSTGRES_URL: postgresql://vsc_owner@haf/haf_block_log
      VSC_MAINNET_HAF_LOG_LEVEL: ${VSC_TEST_LOG_LEVEL:-info}
      VSC_MAINNET_HAF_IPFS_API_URL: ${VSC_TEST_IPFS_API_URL:-http://172.17.0.1:5001}
    command:
      - subindexer
    networks:
      haf-network:
    depends_on:
      vsc-test-install:
        condition: service_completed_successfully
      vsc-test-block-processing:
        condition: service_healthy
      haf:
        condition: service_healthy