services:
  vsc-test-install:
    image: vsc-haf:${VSC_TEST_VERSION:-dev}
    profiles:
      - apps
      - vsc-test
    environment:
      POSTGRES_HOST: haf
    command:
      - install_app
    networks:
      haf-network:
    depends_on:
      haf:
        condition: service_healthy
  vsc-test-uninstall:
    image: vsc-haf:${VSC_TEST_VERSION:-dev}
    profiles:
      - vsc-test-uninstall
    environment:
      POSTGRES_HOST: haf
    command:
      - uninstall_app
    networks:
      haf-network:
    depends_on:
      haf:
        condition: service_healthy
  vsc-test-block-processing:
    image: vsc-haf:${VSC_TEST_VERSION:-dev}
    profiles:
      - apps
      - vsc-test
    environment:
      POSTGRES_URL: postgresql://vsc_owner@haf/haf_block_log
      VSC_HAF_LOG_LEVEL: ${VSC_TEST_LOG_LEVEL:-trace}
    command:
      - process_blocks
    networks:
      haf-network:
    depends_on:
      vsc-test-install:
        condition: service_completed_successfully
      haf:
        condition: service_healthy